apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  replicas: 1
  selector: {matchLabels: {app: demo}}
  template:
    metadata: {labels: {app: demo}}
    spec:
      containers:
      - name: web
        image: REPLACE_ME              # Jenkins swaps in SHA tag
        ports: [{containerPort: 8000}]
